name: "clip_visual"
backend: "onnxruntime"
max_batch_size: 16

input [
  {
    name: "pixel_values"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]

output [
  {
    name: "image_embeddings"
    data_type: TYPE_FP32
    dims: [ 512 ]
  }
]

dynamic_batching {
  preferred_batch_size: [ 4, 8 ]
  max_queue_delay_microseconds: 50000
}

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
